### ISSUE TITLE
Error since Sept. 2

### ISSUE THREAD

**Issue by wangyi041228** [stelar7/lol-parser#12]
java.lang.IllegalStateException: Not a JSON Object: [{"Characters/TFT_Kindred/CharacterRecords/Root":{"mLinkedTraits":["LINK_OFFSET: C7789176","LINK_OFFSET: A2FD51B4"],"mMoveInterval":0.1,"mMoveProximity":720.0,"mMoveRange":500.0,"mMoveHeight":0.0,"mInitialMana":50.0,"mShopData":"LINK_OFFSET: 11C8887E","EF57098F":false,"mCharacterName":"TFT_Kindred","baseHP":600.0,"baseStaticHPRegen":0.0,"healthBarHeight":80.0,"PrimaryAbilityResource":{"AbilityResourceSlotInfo":{"arType":0,"arBase":150.0,"arBaseStaticRegen":0.0}},"BaseDamage":60.0,"baseArmor":20.0,"baseSpellBlock":20.0,"BaseCritChance":0.25,"critDamageMultiplier":1.5,"baseMoveSpeed":550.0,"attackRange":660.0,"AttackSpeed":0.65,"AttackSpeedRatio":0.65,"basicAttack":{"AttackSlotData":{"mAttackCastTime":[0.7],"mAttackDelayCastOffsetPercent":[-0.125],"mAttackProbability":[0.5],"mAttackName":["TFT_KindredBasicAttack"]}},"ExtraAttacks":[{"AttackSlotData":{"mAttackDelayCastOffsetPercent":[-0.125],"mAttackProbability":[0.5],"mAttackName":["TFT_KindredBasicAttack2"]}}],"critAttacks":[{"AttackSlotData":{"mAttackDelayCastOffsetPercent":[-0.1245614],"mAttackName":["TFT_KindredCritAttack"]}}],"expGivenOnDeath":0.0,"goldGivenOnDeath":0.0,"spellNames":["TFT_KindredR","BaseSpell","BaseSpell","BaseSpell"],"extraSpells":["TFT_KindredWPassiveHealMissile","TFT_KindredMarkoftheTFT_KindredSpell","TFT_KindredFakeCastTimeSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell","BaseSpell"],"passiveRange":2.0,"unitTagsString":"Champion","Flags":9446656,"mPreferredPerkStyle":"LINK_OFFSET: Perks/Styles/Inspiration"}}]

	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at types.util.TestTFTData.lambda$buildTFTDataFiles$3(TestTFTData.java:131)
	at types.util.TestTFTData.buildTFTDataFiles(TestTFTData.java:335)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by stelar7** [comment]
not really an issue, since this project is not ment to support TFT. But ill take a look at it once i get home.
